### ISSUE TITLE
sync opened device keymap

### ISSUE THREAD

**Issue by adamrocker** [yoichiro/remap#62]
Remap might be able to sync it if the other app change the keyboard's keymap.

**Comment by yoichiro** [comment]
Probably, this feature can't be implemented. Because if other app opens the keyboard at the same time, all responses will be sent to both Remap and other app. Due to this behavior, I changed the code to close the keyboard on Remap when unexpected response is received. Of course, this behavior includes the case of that Remap are opened in multiple tabs as well.
